steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/helpful-binder-429515-u1/qr-cloud-api', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/helpful-binder-429515-u1/qr-cloud-api']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'qr-cloud-api', '--image', 'gcr.io/helpful-binder-429515-u1/qr-cloud-api', '--platform', 'managed', '--region', 'us-central1']

images:
  - 'gcr.io/helpful-binder-429515-u1/qr-cloud-api'

options:
  logging: CLOUD_LOGGING_ONLY
